// Karma West Bengal Government Jobs & Vacancies Structured Database
// Structured as standard global variable for compatibility with local file:// runs.

const JOBS_DATA = [
  {
    id: "wbpsc-clerk-2026",
    dept: "WBPSC",
    deptFull: "Public Service Commission, West Bengal",
    postName: "Clerkship Examination 2026",
    noticeNo: "13/2026",
    vacancies: 3900,
    ageLimit: "18 - 40 Years (Relaxation as per Govt. rules)",
    qualification: "Madhyamik (10th) pass or equivalent, with basic computer operation and typing skills (20 wpm in English or 10 wpm in Bengali).",
    payScale: "Pay Level 6 (₹22,700 - ₹58,500) under WBS (ROPA) Rules 2019, plus DA, HRA, and Medical allowances.",
    category: "Clerical",
    status: "open", // open, soon, admit, results, closed
    statusText: "Apply Online",
    datePosted: "2026-05-10",
    dateDeadline: "2026-06-15",
    admitCardDate: "2026-07-20",
    examDate: "2026-08-09",
    resultsDate: null,
    applyUrl: "https://wbpsc.gov.in/apply-online",
    pdfUrl: "https://wbpsc.gov.in/Download?name=clerkship_2026_detailed_notice.pdf",
    crawlHistory: [
      { date: "2026-05-08 10:15", event: "Short indicative notification scanned on WBPSC portal." },
      { date: "2026-05-10 09:00", event: "Detailed advertisement 13/2026 published. Live vacancy tracker initiated." },
      { date: "2026-05-10 11:30", event: "Online application system activated." }
    ]
  },
  {
    id: "wbpsc-wbcs-2026",
    dept: "WBPSC",
    deptFull: "Public Service Commission, West Bengal",
    postName: "West Bengal Civil Service (Exe.) Examination, 2026",
    noticeNo: "01/2026",
    vacancies: 180,
    ageLimit: "21 - 36 Years (Group A & C), 20 - 36 (Group B - Police Service)",
    qualification: "A degree from a recognized University or equivalent. Ability to read, write and speak in Bengali (not required for candidates whose mother tongue is Nepali).",
    payScale: "Group A: Pay Level 16 (₹56,100 - ₹1,44,300); Group B (WBP): Pay Level 16 (₹56,100 - ₹1,44,300).",
    category: "General Administration",
    status: "admit",
    statusText: "Admit Card Out",
    datePosted: "2026-01-15",
    dateDeadline: "2026-02-28",
    admitCardDate: "2026-05-20",
    examDate: "2026-06-07",
    resultsDate: null,
    applyUrl: "https://wbpsc.gov.in/admit-card-download",
    pdfUrl: "https://wbpsc.gov.in/Download?name=wbcs_2026_prelims_admit_card_notice.pdf",
    crawlHistory: [
      { date: "2026-01-15 14:00", event: "Detailed WBCS 2026 notification published online." },
      { date: "2026-02-28 23:59", event: "Application registration portal closed." },
      { date: "2026-05-20 10:00", event: "Prelims Admit Card download links declared active. Exam centers finalized." }
    ]
  },
  {
    id: "wbpsc-misc-2025",
    dept: "WBPSC",
    deptFull: "Public Service Commission, West Bengal",
    postName: "Miscellaneous Services Recruitment Examination (Final)",
    noticeNo: "11/2025",
    vacancies: 450,
    ageLimit: "20 - 39 Years",
    qualification: "A degree from a recognized University or its equivalent, and basic knowledge of Bengali.",
    payScale: "Pay Level 10 (₹32,100 - ₹82,900) for posts like Inspector, Block Welfare Officer, etc.",
    category: "General Administration",
    status: "results",
    statusText: "Results Declared",
    datePosted: "2025-09-05",
    dateDeadline: "2025-10-10",
    admitCardDate: "2025-12-15",
    examDate: "2026-01-18",
    resultsDate: "2026-05-22",
    applyUrl: "https://wbpsc.gov.in/results-portal",
    pdfUrl: "https://wbpsc.gov.in/Download?name=miscellaneous_2025_final_results_list.pdf",
    crawlHistory: [
      { date: "2025-09-05 11:00", event: "Notice launched on portal." },
      { date: "2026-01-18 17:00", event: "Written examination completed successfully across all district centers." },
      { date: "2026-05-22 16:30", event: "Scanned & detected final merit list PDF uploaded on WBPSC portal. Congratulations to selected candidates!" }
    ]
  },
  {
    id: "wbprb-constable-2026",
    dept: "WBPRB",
    deptFull: "West Bengal Police Recruitment Board",
    postName: "Constable in West Bengal Police - 2026",
    noticeNo: "WBP/2026/CONS-04",
    vacancies: 8400,
    ageLimit: "18 - 30 Years (Upper age relaxed by 5 years for SC/ST and 3 years for OBC)",
    qualification: "Passed Madhyamik (10th) examination from West Bengal Board of Secondary Education or its equivalent. Candidate must be fit in Physical Standards (Height, Weight, Chest).",
    payScale: "Pay Level 6 (₹22,700 - ₹58,500) plus admissible allowances.",
    category: "Police & Defense",
    status: "open",
    statusText: "Apply Online",
    datePosted: "2026-05-01",
    dateDeadline: "2026-06-05",
    admitCardDate: "2026-07-05",
    examDate: "2026-07-26",
    resultsDate: null,
    applyUrl: "https://prb.wb.gov.in/constable-recruitment-2026",
    pdfUrl: "https://prb.wb.gov.in/Download?notice=constable_2026_wbp_detailed.pdf",
    crawlHistory: [
      { date: "2026-04-28 17:00", event: "Indicative advertisement scanned on WBP Board site." },
      { date: "2026-05-01 00:01", event: "Detailed notification and online apply link active. Server response normal." }
    ]
  },
  {
    id: "wbprb-si-2026",
    dept: "WBPRB",
    deptFull: "West Bengal Police Recruitment Board",
    postName: "Sub-Inspector (SI) / Lady SI in West Bengal Police",
    noticeNo: "WBP/2026/SI-05",
    vacancies: 460,
    ageLimit: "20 - 30 Years",
    qualification: "Bachelor's Degree in any discipline from a recognized university or its equivalent. Physical Measurement and Efficiency Test (PET/PMT) clearance required.",
    payScale: "Pay Level 10 (₹32,100 - ₹82,900) plus high-risk allowances.",
    category: "Police & Defense",
    status: "soon",
    statusText: "Coming Soon",
    datePosted: "2026-05-24",
    dateDeadline: "2026-07-15",
    admitCardDate: null,
    examDate: null,
    resultsDate: null,
    applyUrl: "https://prb.wb.gov.in/si-recruitment-2026",
    pdfUrl: "https://prb.wb.gov.in/Download?notice=si_2026_upcoming_announcement.pdf",
    crawlHistory: [
      { date: "2026-05-24 12:00", event: "Draft rules and upcoming SI notification cleared by state Cabinet. Detected entry." }
    ]
  },
  {
    id: "wbhrb-nurse-2026",
    dept: "WBHRB",
    deptFull: "West Bengal Health Recruitment Board",
    postName: "Staff Nurse, Grade II (GNM & B.Sc Nursing)",
    noticeNo: "HRB/2026/NUR-02",
    vacancies: 1200,
    ageLimit: "18 - 39 Years",
    qualification: "General Nursing and Midwifery (GNM) or B.Sc. (Nursing) passed from any Nursing Training School recognized by West Bengal Nursing Council. Registration as Nurse-Midwife in West Bengal Nursing Council.",
    payScale: "Pay Level 9 (₹29,800 - ₹76,800) under WBS (ROPA) 2019, plus uniform, laundry, and risk allowances.",
    category: "Health & Medical",
    status: "open",
    statusText: "Apply Online",
    datePosted: "2026-05-15",
    dateDeadline: "2026-06-10",
    admitCardDate: "2026-06-30",
    examDate: "2026-07-12",
    resultsDate: null,
    applyUrl: "https://www.wbhrb.in/online-application",
    pdfUrl: "https://www.wbhrb.in/Download?notice=staff_nurse_grade_II_2026.pdf",
    crawlHistory: [
      { date: "2026-05-12 18:30", event: "Portal database changes detected. GNM criteria updated." },
      { date: "2026-05-15 10:00", event: "Official portal registration link for Nurse recruitment declared open." }
    ]
  },
  {
    id: "wbhrb-mo-2026",
    dept: "WBHRB",
    deptFull: "West Bengal Health Recruitment Board",
    postName: "Medical Officer (Specialist) & GDMO",
    noticeNo: "HRB/2026/MO-01",
    vacancies: 680,
    ageLimit: "36 Years for General, 40 Years for Specialists",
    qualification: "MBBS degree included in the First or Second Schedule or Part-II of the Third Schedule of IMC Act. Specialization PG Degree for MO (Specialist). Registration in West Bengal Medical Council.",
    payScale: "Pay Level 16 (₹56,100 - ₹1,44,300) plus Non-Practicing Allowance (NPA) of 20%.",
    category: "Health & Medical",
    status: "soon",
    statusText: "Coming Soon",
    datePosted: "2026-05-24",
    dateDeadline: "2026-07-01",
    admitCardDate: null,
    examDate: null,
    resultsDate: null,
    applyUrl: "https://www.wbhrb.in/mo-portal",
    pdfUrl: "https://www.wbhrb.in/Download?notice=mo_specialist_gdmo_indicative.pdf",
    crawlHistory: [
      { date: "2026-05-24 16:00", event: "Health Department requisition list released. Anticipated release within 3 weeks." }
    ]
  },
  {
    id: "wbbpe-primary-2026",
    dept: "WBBPE",
    deptFull: "West Bengal Board of Primary Education",
    postName: "Primary School Teacher Recruitment Examination 2026",
    noticeNo: "BPE/2026/TET-RE-08",
    vacancies: 4200,
    ageLimit: "18 - 40 Years",
    qualification: "Higher Secondary (12th) with at least 50% marks and 2-year Diploma in Elementary Education (D.El.Ed), OR Bachelor's degree and D.El.Ed. Cleared WB TET (Teacher Eligibility Test).",
    payScale: "Basic Pay: ₹28,900 plus DA, HRA, and school allowance.",
    category: "Education & Teaching",
    status: "open",
    statusText: "Apply Online",
    datePosted: "2026-05-05",
    dateDeadline: "2026-06-08",
    admitCardDate: "2026-07-10",
    examDate: "2026-08-02",
    resultsDate: null,
    applyUrl: "https://www.wbbpe.org/teacher-recruitment-portal",
    pdfUrl: "https://www.wbbpe.org/Download?notice=primary_recruitment_2026_official.pdf",
    crawlHistory: [
      { date: "2026-05-03 12:00", event: "High Court order alignment checks performed by Board." },
      { date: "2026-05-05 10:30", event: "Application registration portal declared live for TET 2022/2024 cleared candidates." }
    ]
  },
  {
    id: "wbssc-slst-2026",
    dept: "WBSSC",
    deptFull: "West Bengal School Service Commission",
    postName: "Assistant Teacher Recruitment (IX-XII) - 1st SLST",
    noticeNo: "SSC/2026/SLST-01",
    vacancies: 2800,
    ageLimit: "21 - 40 Years",
    qualification: "Graduate/Post Graduate from recognized university with at least 50% marks in respective school subject and Bachelor of Education (B.Ed.) from NCTE recognized institution.",
    payScale: "Pay Level 11 (₹33,400 - ₹86,100) for Post-Graduate Teachers.",
    category: "Education & Teaching",
    status: "soon",
    statusText: "Coming Soon",
    datePosted: "2026-05-24",
    dateDeadline: "2026-07-31",
    admitCardDate: null,
    examDate: null,
    resultsDate: null,
    applyUrl: "https://www.westbengalssc.com/slst-apply",
    pdfUrl: "https://www.westbengalssc.com/Download?notice=slst_2026_draft_regulations.pdf",
    crawlHistory: [
      { date: "2026-05-24 15:45", event: "Draft guidelines for SLST subject exams scanned on WBSSC homepage. Crawled successfully." }
    ]
  },
  {
    id: "wbjeeb-anm-2026",
    dept: "WBJEEB",
    deptFull: "West Bengal Joint Entrance Examinations Board",
    postName: "Joint Entrance for ANM(R) & GNM-2026",
    noticeNo: "JEEB/2026/ANM-GNM-03",
    vacancies: 1150,
    ageLimit: "17 - 35 Years",
    qualification: "Passed Higher Secondary (10+2) from West Bengal Council of Higher Secondary Education or its equivalent with English as one of the subjects, securing at least 40% aggregate marks.",
    payScale: "Admission Entrance Exam for state government hospital training seats with stipend.",
    category: "Technical & Medical",
    status: "closed",
    statusText: "Closed",
    datePosted: "2026-02-10",
    dateDeadline: "2026-03-20",
    admitCardDate: "2026-05-02",
    examDate: "2026-05-17",
    resultsDate: null,
    applyUrl: "https://wbjeeb.nic.in/anm-gnm",
    pdfUrl: "https://wbjeeb.nic.in/Download?notice=anm_gnm_2026_information_bulletin.pdf",
    crawlHistory: [
      { date: "2026-02-10 10:00", event: "Information Bulletin uploaded. Registrations opened." },
      { date: "2026-03-20 23:59", event: "Application and payment window closed." },
      { date: "2026-05-17 14:00", event: "ANM & GNM-2026 entrance exam successfully concluded. Scraper tracking answer keys." }
    ]
  }
];
